name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Please provide as much information as possible in order to help us address your issue!"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If possible, also provide links to your used mods.
      placeholder: Tell us what the issue is!
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: Which Minecraft version are you using?
      multiple: false
      options:
        - 1.20.4
        - 1.20.3
        - 1.20.2
        - 1.20.1
        - 1.20
        - Other (unsupported)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Modloader (Fabric/Forge)
      description: Which Modloader are you using?
      multiple: false
      options:
        - Fabric
        - Forge
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: World-Preview Version
      description: Which version of World-Preview are you using?
      multiple: false
      options:
        - 1.1.5
        - 1.1.4
        - 1.1.3
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0.0
        - Other (unsupported)
      default: 0
    validations:
      required: true
  - type: textarea
    id: mc-logs
    attributes:
      label: Minecraft Logs
      description: See [this guide for getting the latest minecraft logs](https://minecrafthopper.net/help/guides/getting-minecraft-latest-log/)!
      placeholder: Paste your latest Minecraft log here!
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Additional Information 
      description: For any other helpful details!
      placeholder: Any additional information, such as screenshots (if applicable) or more context.
    validations:
      required: false
      
